- name: build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_eth1.ipv4.address is defined
  with_items: "{{ groups['all'] }}"

- name: disable selinux
  selinux: state=disabled

- name: disable of selinux - now
  command: setenforce 0

- name: Ensure net.bridge.bridge-nf-call-iptables is set. See kubeadm
  copy: src=k8s.conf owner=root group=root dest=/etc/sysctl.d/k8s.conf

- name: Run sysctl
  command: sysctl --system

- name: Add Kubernetes yum repo
  yum_repository:
    name: kubernetes
    description: Kubernetes kubeadm
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    gpgcheck: yes

- name: install utility programs
  yum: name={{ item }} state=present disable_gpg_check=yes
  with_items:
    - etcd
    - wget
    - ntp
    - screen
    - epel-release
    - vim
    - iptables
    - iptables-utils
    - iptables-services
    - ncurses-term
    - kubelet
    - kubeadm
    - kubectl
    - kernel-devel
    - kernel-headers

- name: install epel  utility programs
  yum: name={{ item }} state=present disable_gpg_check=yes
  with_items:
    - jq
    - lvm2
    - yum-utils
    - device-mapper-persistent-data

- name: remove all old docker
  yum: name={{ item }} state=removed disable_gpg_check=yes
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

- name: install docker ce yum repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker ce
  yum: name=docker-ce state=present disable_gpg_check=yes

- name: enable kube services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - docker
    - ntpd
    - kubelet

- name: download crictl
  get_url:
    url: https://github.com/kubernetes-incubator/cri-tools/releases/download/v1.0.0-beta.0/crictl-v1.0.0-beta.0-linux-amd64.tar.gz
    dest: /home/vagrant/crictl.tar.gz

- name: install crictl
  unarchive:
    src: /home/vagrant/crictl.tar.gz
    remote_src: yes
    dest: /bin

- name: turn off swap
  command: swapoff -a

- name: remove swap from /etc/fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: "swap"


