- name: install v1.17 kubernetes
  yum: name={{ packages }} state=present disable_gpg_check=yes
  vars:
    packages:
      - kubelet-1.17.15-0
      - kubeadm-1.17.15-0
      - kubectl-1.17.15-0

- name: setting vars
  set_fact:
    kubeadm_kubernetes_version: stable-1.17
    use_dockerce: true
