- name: initialize kubeadm on master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --token={{ kubernetes_token }} --apiserver-advertise-address={{ ansible_eth1.ipv4.address }}
  when: kubeadm_kubernetes_version is not defined

- name: initialize kubeadm on master
  command: kubeadm init --kubernetes-version={{ kubeadm_kubernetes_version }} --pod-network-cidr=10.244.0.0/16 --token={{ kubernetes_token }} --apiserver-advertise-address={{ ansible_eth1.ipv4.address }}
  when: kubeadm_kubernetes_version is defined

- name: create flannel network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/960b3243b9a7faccdfe7b3c09097105e68030ea7/Documentation/kube-flannel.yml

- name: get kubeconfig.conf
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: kubeconfig.conf
    flat: yes

