- name: initialize kubeadm on master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --token={{ kubernetes_token }} --apiserver-advertise-address={{ ansible_eth1.ipv4.address }}

- name: create flannel network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml

- name: get kubeconfig.conf
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: kubeconfig.conf
    flat: yes
    
